/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Reservation;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author jayaw
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    public void resetcolor(JPanel panel){
        panel.setBackground(new Color(73, 89, 235));
    }
    
    public void setcolor(JPanel panel){
        panel.setBackground(new Color(85, 242, 240));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                MainPanel = new javax.swing.JPanel();
                SidePanel = new javax.swing.JPanel();
                txt_searchBox = new javax.swing.JTextField();
                btn_search = new javax.swing.JLabel();
                HomeBtn = new javax.swing.JPanel();
                Home_icon = new javax.swing.JLabel();
                Home_lable = new javax.swing.JLabel();
                GuideBtn = new javax.swing.JPanel();
                Guide_icon = new javax.swing.JLabel();
                Guide_lable = new javax.swing.JLabel();
                FeedbackBtn = new javax.swing.JPanel();
                Feedback_icon = new javax.swing.JLabel();
                Feedback_lable = new javax.swing.JLabel();
                AppLogo = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                TabbedPane = new javax.swing.JTabbedPane();
                Home = new javax.swing.JPanel();
                HomeImg = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jPanel1 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                customer = new javax.swing.JTextField();
                jScrollPane3 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();
                jButton1 = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                jScrollPane5 = new javax.swing.JScrollPane();
                jTextArea2 = new javax.swing.JTextArea();
                jPanel3 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTextArea1 = new javax.swing.JTextArea();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel4 = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setUndecorated(true);

                MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                SidePanel.setBackground(new java.awt.Color(24, 24, 24, 80));

                txt_searchBox.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txt_searchBoxActionPerformed(evt);
                        }
                });

                btn_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
                btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btn_searchMouseClicked(evt);
                        }
                });

                HomeBtn.setBackground(new java.awt.Color(85, 242, 240));
                HomeBtn.setToolTipText("");
                HomeBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseMoved(java.awt.event.MouseEvent evt) {
                                HomeBtnMouseMoved(evt);
                        }
                });
                HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                HomeBtnMouseClicked(evt);
                        }
                });

                Home_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                Home_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home .png"))); // NOI18N

                Home_lable.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
                Home_lable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                Home_lable.setText("      HOME");

                javax.swing.GroupLayout HomeBtnLayout = new javax.swing.GroupLayout(HomeBtn);
                HomeBtn.setLayout(HomeBtnLayout);
                HomeBtnLayout.setHorizontalGroup(
                        HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HomeBtnLayout.createSequentialGroup()
                                .addComponent(Home_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Home_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                HomeBtnLayout.setVerticalGroup(
                        HomeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Home_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(Home_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                GuideBtn.setBackground(new java.awt.Color(85, 242, 240));
                GuideBtn.setToolTipText("");
                GuideBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseMoved(java.awt.event.MouseEvent evt) {
                                GuideBtnMouseMoved(evt);
                        }
                });
                GuideBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                GuideBtnMouseClicked(evt);
                        }
                });

                Guide_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                Guide_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/users-alt.png"))); // NOI18N

                Guide_lable.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
                Guide_lable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                Guide_lable.setText("      GUIDE");

                javax.swing.GroupLayout GuideBtnLayout = new javax.swing.GroupLayout(GuideBtn);
                GuideBtn.setLayout(GuideBtnLayout);
                GuideBtnLayout.setHorizontalGroup(
                        GuideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(GuideBtnLayout.createSequentialGroup()
                                .addComponent(Guide_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Guide_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                GuideBtnLayout.setVerticalGroup(
                        GuideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Guide_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(Guide_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                FeedbackBtn.setBackground(new java.awt.Color(85, 242, 240));
                FeedbackBtn.setToolTipText("");
                FeedbackBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                        public void mouseMoved(java.awt.event.MouseEvent evt) {
                                FeedbackBtnMouseMoved(evt);
                        }
                });
                FeedbackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                FeedbackBtnMouseClicked(evt);
                        }
                });

                Feedback_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                Feedback_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/profiles.png"))); // NOI18N

                Feedback_lable.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
                Feedback_lable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                Feedback_lable.setText("      FEEDBACK");

                javax.swing.GroupLayout FeedbackBtnLayout = new javax.swing.GroupLayout(FeedbackBtn);
                FeedbackBtn.setLayout(FeedbackBtnLayout);
                FeedbackBtnLayout.setHorizontalGroup(
                        FeedbackBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(FeedbackBtnLayout.createSequentialGroup()
                                .addComponent(Feedback_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Feedback_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                FeedbackBtnLayout.setVerticalGroup(
                        FeedbackBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Feedback_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(Feedback_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/200×150 .png"))); // NOI18N

                javax.swing.GroupLayout AppLogoLayout = new javax.swing.GroupLayout(AppLogo);
                AppLogo.setLayout(AppLogoLayout);
                AppLogoLayout.setHorizontalGroup(
                        AppLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                AppLogoLayout.setVerticalGroup(
                        AppLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
                SidePanel.setLayout(SidePanelLayout);
                SidePanelLayout.setHorizontalGroup(
                        SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GuideBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                                .addGap(0, 14, Short.MAX_VALUE)
                                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AppLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(SidePanelLayout.createSequentialGroup()
                                                .addComponent(txt_searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12))
                        .addComponent(FeedbackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                SidePanelLayout.setVerticalGroup(
                        SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SidePanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_searchBox, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                        .addComponent(btn_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addComponent(AppLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(GuideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(FeedbackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(275, Short.MAX_VALUE))
                );

                MainPanel.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

                HomeImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                HomeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/WaterFAll (2).jpg"))); // NOI18N

                javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
                Home.setLayout(HomeLayout);
                HomeLayout.setHorizontalGroup(
                        HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HomeLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(HomeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                HomeLayout.setVerticalGroup(
                        HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(HomeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 529, Short.MAX_VALUE)
                );

                TabbedPane.addTab("tab1", Home);

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));
                jPanel1.setForeground(new java.awt.Color(153, 0, 0));
                jPanel1.setPreferredSize(new java.awt.Dimension(740, 600));

                jLabel5.setBackground(new java.awt.Color(204, 204, 204));
                jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(51, 51, 51));
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("Customer Name");

                jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(0, 0, 0));
                jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel6.setText("Feedback");

                customer.setEditable(false);
                customer.setBackground(new java.awt.Color(204, 204, 204));

                jTable2.setAutoCreateColumnsFromModel(false);
                jTable2.setBackground(new java.awt.Color(204, 204, 204));
                jTable2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                jTable2.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null},
                                {null, null},
                                {null, null},
                                {null, null}
                        },
                        new String [] {
                                "Customer_name", "Feedback"
                        }
                ));
                jTable2.setEnabled(false);
                jScrollPane3.setViewportView(jTable2);

                jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                jButton1.setText("Submit");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jLabel7.setBackground(new java.awt.Color(102, 102, 102));
                jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(0, 0, 0));
                jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel7.setText("REVIEW FEEDBACK");
                jLabel7.setEnabled(false);

                jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
                jTextArea2.setColumns(20);
                jTextArea2.setRows(5);
                jScrollPane5.setViewportView(jTextArea2);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(94, 94, 94))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(84, 84, 84))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(104, 104, 104)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(220, 220, 220)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(33, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(84, 84, 84)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(customer, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))
                );

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                );

                TabbedPane.addTab("tab2", jPanel2);

                jLabel2.setBackground(new java.awt.Color(0, 102, 0));
                jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setText("REVIEW FEEDBACK");

                jLabel3.setBackground(new java.awt.Color(153, 153, 153));
                jLabel3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
                jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel3.setText("Customer");

                jLabel4.setBackground(new java.awt.Color(255, 255, 51));
                jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
                jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel4.setText("Feedback");

                jTextField1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

                jTextArea1.setColumns(20);
                jTextArea1.setRows(5);
                jScrollPane1.setViewportView(jTextArea1);

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane2.setViewportView(jTable1);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(177, Short.MAX_VALUE))
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                TabbedPane.addTab("tab3", jPanel3);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 740, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 529, Short.MAX_VALUE)
                );

                TabbedPane.addTab("tab4", jPanel4);

                MainPanel.add(TabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 740, 560));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                );

                setSize(new java.awt.Dimension(990, 559));
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void GuideBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuideBtnMouseClicked
        // TODO add your handling code here:
        TabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_GuideBtnMouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        // TODO add your handling code here:
        TabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        // TODO add your handling code here:
        String search = txt_searchBox.getText();
        if(search.equals("guide") || search.equals("Guide") || search.equals("GUIDE")){
            TabbedPane.setSelectedIndex(1);
        }
    }//GEN-LAST:event_btn_searchMouseClicked

    private void txt_searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchBoxActionPerformed

    private void FeedbackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackBtnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FeedbackBtnMouseClicked

    private void HomeBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseMoved
        // TODO add your handling code here:
        setcolor(HomeBtn);
        resetcolor(GuideBtn);
        resetcolor(FeedbackBtn);
    }//GEN-LAST:event_HomeBtnMouseMoved

    private void GuideBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuideBtnMouseMoved
        // TODO add your handling code here:
        setcolor(GuideBtn);
        resetcolor(HomeBtn);
        resetcolor(FeedbackBtn);
    }//GEN-LAST:event_GuideBtnMouseMoved

    private void FeedbackBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FeedbackBtnMouseMoved
        // TODO add your handling code here:
        setcolor(FeedbackBtn);
        resetcolor(HomeBtn);
        resetcolor(GuideBtn);
    }//GEN-LAST:event_FeedbackBtnMouseMoved

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                String name = customer.getText();
                String fdback = feedback.getText();

                if(name.trim().equals("") || fdback.trim().equals(""))
                {
                        JOptionPane.showMessageDialog(null,"One or More Fields Are Empty","Empty Fields",2);
                }

                else{

                        try {
                                Class.forName("com.mysql.cj.jdbc.Driver");
                                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/nethmi", "root","");

                                String sql = "INSERT INTO feedback VALUES(?,?)";
                                PreparedStatement ptst = con.prepareStatement(sql);

                                ptst.setString(1,name);
                                ptst.setString(2,fdback);
                                ptst.executeUpdate();
                                JOptionPane.showMessageDialog(this," Successfully");
                                // con.close();

                                String sql1 = "SELECT * FROM feedback ";
                                PreparedStatement ptst1 = con.prepareStatement(sql1);

                                ptst1.executeQuery();
                                jTable1.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(ptst1.executeQuery()));

                                con.close();
                        }catch (Exception e) {
                                JOptionPane.showMessageDialog(this,e);
                        }
                }

        }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel AppLogo;
        private javax.swing.JPanel FeedbackBtn;
        private javax.swing.JLabel Feedback_icon;
        private javax.swing.JLabel Feedback_lable;
        private javax.swing.JPanel GuideBtn;
        private javax.swing.JLabel Guide_icon;
        private javax.swing.JLabel Guide_lable;
        private javax.swing.JPanel Home;
        private javax.swing.JPanel HomeBtn;
        private javax.swing.JLabel HomeImg;
        private javax.swing.JLabel Home_icon;
        private javax.swing.JLabel Home_lable;
        private javax.swing.JPanel MainPanel;
        private javax.swing.JPanel SidePanel;
        private javax.swing.JTabbedPane TabbedPane;
        private javax.swing.JLabel btn_search;
        private javax.swing.JTextField customer;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane5;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextArea jTextArea2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField txt_searchBox;
        // End of variables declaration//GEN-END:variables
}
